### ISSUE TITLE
Structorizer does not start

### ISSUE THREAD

**Issue by Dnk1287** [fesch/Structorizer.Desktop#1076]
I use Structorizer with Windows 10, updated to version 3.32-11 and now it won't start anymore.
I have JRE installed and up-to-date (version 8.351).
With 'java -jar -verbose structorizer.jar' I produced the following traces which show an exception at the end.
[structorizer_trace.txt](https://github.com/fesch/Structorizer.Desktop/files/9917442/structorizer_trace.txt)

**Comment by codemanyak** [comment]
Thank you for the interesting trace. But please let's make it short: You need Java 11 or newer to start Structorizer versions >= 3.32. Please see [news page](https://structorizer.fisch.lu/index.php?include=news) entry from 2021-09-19, [User Guide installation page](https://help.structorizer.fisch.lu/index.php?menu=45) and e.g. issues #998, #1028, #1031, #1070.

**Comment by codemanyak** [comment]
@Dnk1287 Please let us know when the installation of a Java RE or JDK of version 11 or later solved your problem (as we expect it will).

**Comment by Dnk1287** [comment]
I installed AdoptopenJDK (version 17 I think) and Structorizer works flawless again.

The only thing I can add is the suggestion to let Structorizer on startup check if the (open)JDK/JRE meets the requirements for Structorizer and if not present a message top the user.

**Comment by codemanyak** [comment]
@Dnk1287 
Thanks for your feedback. You wrote:
> The only thing I can add is the suggestion to let Structorizer on startup check if the (open)JDK/JRE meets the requirements for Structorizer and if not present a message to the user.

For the script-based launch this has been incorporated, but for the Windows installer pack we made Launch4J responsible to do this job. Obviously, it doesn't satisfyingly do so. We will think of an improvement there.

**Comment by Dnk1287** [comment]
The setup I used was Structorizer.exe, version 3.32.11 .
I removed the installation and its folder when Structorizer didn't start and did a new install.
The installation folder contains files as in here:
[structorizer-dir.txt](https://github.com/fesch/Structorizer.Desktop/files/9935881/structorizer-dir.txt)

**Comment by codemanyak** [comment]
@Dnk1287 
Thanks for the directory listing. The content looks okay. So I really wonder why the launcher did not pop up a window like the one shown in issue #1030. (But perhaps it did and you just didn't bother to mention it?) I will care for the error box showing the title "Structorizer" from the next version on, but even the recent launcher configuration should ensure that the required Java version gets reported with that kind of message box whenever the launcher identifies a Java version older than 11(.0.1).
Well, be that as it may, I am glad that on your site the problem has been solved:
> I installed AdoptopenJDK (version 17 I think) and Structorizer works flawlessly again.

So enjoy working with Structorizer. We will further observe the launcher behaviour and try to find out what specific cases induce an insufficient user information.

**Comment by Dnk1287** [comment]
You're welcome and I certainly enjoy using Structorizer, both on Linux and on Windows (in that order of preference).
I certainly did not get any message. I'm a software developer and know the importance of messages.
I tried several times, from command line, from the Windows menu, after update and after uninstall plus clean install.
The splash screen appears (Structorizer icon) and then disappears, that's all. No logging in Windows log books either.

HTH, and again, thank you for your help.

**Comment by raulus127** [comment]
The same happens to me. I installed the AdoptopenJDK 16 and it still doesn't work. I'm trying to run it on W11.

**Comment by codemanyak** [comment]
@raulus127 
> The same happens to me. I installed the AdoptopenJDK 16 and it still doesn't work. I'm trying to run it on W11.

Did you activate the respective checkboxes for JAVE_HOME environment variable and the "JavaSoft (Oracle) registry entries" on installing AdoptOpenJDK, as recommended in the [User Guide](https://help.structorizer.fisch.lu/index.php?menu=466&page=#open_jdk_trouble)? I thought we had tackled your troubles on issue #1031 already?

**Comment by codemanyak** [comment]
@raulus127 
I'd like to add that [Adoptium](https://adoptium.net/temurin/releases/) meanwhile also offers JRE downloads, not only JDKs. So, if you don't hppen to develop yourself with Java, you might give a JRE installation a try.

**Comment by codemanyak** [comment]
Version 3.32-13 should have solved the aspects of this issue - the analysis of #1100 led to the solution.
