### ISSUE TITLE
COBOL-Import: IndexOutOfBoundsException on parsing empty single-quoted strings

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#626]
Happens in COBOL-Parser, during internal conversion of `''` to `""`.
Will PR this soon.

**Comment by GitMensch** [comment]
Fix is available in bugfix branch, merged by @codemanyak.

Question: Do we close this issue now manually or will it be auto-closed when bugfix branch is merged to master?

**Comment by codemanyak** [comment]
It will be auto-closed on merging it to master for the next release. So other people by chance bumping into the same problem may be aware that we are working on the problem and the fix is prepared but still not delivered.

**Comment by codemanyak** [comment]
Empty strings (`''` or `""`) now pass the parser but then the builder fails to interpret the input properly.
In code like the following, the one empty string (third line) is converted either to nothing (single quotes) or to a single backslash-escaped quote (double quotes, see code snippet and screenshot detail), which both produces a defective concatenation.
```COBOL
       01  table-messages.
           02 table-messages-defined value
               ""
             & "   This program shows how alternate keys are used."
             & "The first field in the record is the primary key, "
             & "and the second is the alternate key.              "
             & "                                                  "
             & "   Blank alternate keys do not appear in the read "
             & "loop because of the 'suppress when spaces' clause."
             & "As an exercise, comment out the clause and see    "
             & "the difference when the program is run again.     "
             & "                                                  "
             & "1)  The file is opened output, to create it.      "
             & "2)  Six sample records are written, some with     "
             & "    blank alternate keys.                         "
             & "3)  The file is opened i-o, for read, rewrite,    "
             & "    and delete functions.                         "
             & "4)  Record 6, with a blank key, is rewritten with "
             & "    non blank key.                                "
             & "5)  The file is started on the alternate key,     "
             & "    so that read next statements read by the      "
             & "    alternate key and not by the primary key.     "
             & "6)  The records are read until there are no more  "
             & "    alternate keys.                               "
             & "7)  After all of the records are read, the first  "
             & "    non blank alternate key record is either      "
             & "    rewritten with a blank alternate key or       "
             & "    deleted.                                      "
             & "8)  The file is started again in step 5) and      "
             & "    the process repeated until there are no       "
             & "    more records with non blank alternate keys.   "
             & "                                                  ".
           02 table-message redefines table-messages-defined
              pic x(50) occurs 30 times.
```
![grafik](https://user-images.githubusercontent.com/15326471/47466963-29ea1980-d7f4-11e8-8e67-b223f755c43a.png)

**Comment by GitMensch** [comment]
I'll have a look at this one.

**Comment by GitMensch** [comment]
I consider this fixed with #634, also removes recompilation of patterns and recreating pattern/matcher objects for any string literal.

Side note: Can you (again?) add line breaks in the diagram generation? This long line looks really bad and the original split was like done with a reason ;-)

**Comment by codemanyak** [comment]
> Side note: Can you (again?) add line breaks in the diagram generation? This long line looks really bad and the original split was like done with a reason ;-)

You refer to #416. I will reconsider this issue ASAP (which will not be within this week).

**Comment by GitMensch** [comment]
Yes, #416 was the issue. I obviously forgot that this one was still "open".

> But remember that the original line breaks aren't available for the diagram generation since they have been filtered by the parser, they don't show up in the reduction tree.

A simple heuristic of the resulting line length would do the trick - if it is too long then split into multiple lines.
